# This is a basic workflow to help you get started with Actions

name: Build and Deploy Collections

on:
  push:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy Collections
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
